/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestApp;
import JFXGrid.core.Axis;
import JFXGrid.core.JFXHeatmap;
import JFXGrid.data.JFXDatasetFactory;
import JFXGrid.events.JFXClock;
import JFXGrid.plugin.GridPlayer;
import JFXGrid.util.Style;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.stage.Stage;
import org.apache.commons.lang3.ArrayUtils;
import org.ojalgo.matrix.MatrixR032;
import org.ojalgo.random.Uniform;

public class App extends Application {

    public static void main(String[] args) {
        launch();

    }

    @Override
    public void start(Stage stage) throws Exception {

        var heatmap = new JFXHeatmap();
        var player = new GridPlayer();

        heatmap.addPlugin(player);
        heatmap.getGridStyler().setStyle(Style.DUOTONE);
        heatmap.getGridStyler().setShowLines(false);
        heatmap.setPrefHeight(300);
        heatmap.setPrefWidth(300);

        var dataFactory = new JFXDatasetFactory(32, 32).add(MatrixR032.FACTORY.makeFilled(256, 256, Uniform.standard()));
        for(int i = 0; i < 1000; i++) {
            dataFactory.add(MatrixR032.FACTORY.makeFilled(32, 32, Uniform.standard()));
        }
        heatmap.setDataset(dataFactory.build());

        JFXClock.get().setFpsCap(100);
        JFXClock.get().addFixedTickListener(() -> {
            if(heatmap.getDataset().getFrameNum()%7 == 0) {
                System.out.println("FPS: " + heatmap.getRendererFPS());
            }
        });

        player.play();

        JFXClock.get().start();
        Scene scene = new Scene(heatmap);

        stage.setScene(scene);
        stage.setWidth(600);
        stage.setHeight(400);
        stage.show();
    }

    @Override
    public void stop() throws Exception {
        JFXClock.get().setRunning(false);
    }
}
