/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestApp;
import JFXGrid.core.Axis;
import JFXGrid.core.JFXHeatmap;
import JFXGrid.events.JFXClock;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.stage.Stage;

public class App extends Application {

    public static void main(String[] args) {
        launch();

    }

    @Override
    public void start(Stage stage) throws Exception {

        var heatmap = new JFXHeatmap();
        Parent root = new Pane(heatmap);
        AnchorPane.setTopAnchor(heatmap, 10d);
        AnchorPane.setBottomAnchor(heatmap, 10d);
        AnchorPane.setLeftAnchor(heatmap, 10d);
        AnchorPane.setRightAnchor(heatmap, 10d);
        heatmap.setMinHeight(300);
        heatmap.setPrefHeight(300);
        heatmap.setMinWidth(300);
        heatmap.setPrefWidth(300);

        heatmap.setBackground(new Background(new BackgroundFill(Color.SLATEBLUE, CornerRadii.EMPTY, Insets.EMPTY)));

        JFXClock.get().start();
        JFXClock.get().setFpsCap(100);
//        heatmap.addAxis(new Axis(Axis.Align.Left));
//        heatmap.addAxis(new Axis(Axis.Align.Left));




        Scene scene = new Scene(root);

        stage.setScene(scene);
        stage.setWidth(600);
        stage.setHeight(400);
        stage.show();
    }
}
