/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestApp;
import JFXGrid.JFXGrid;
import JFXGrid.javafx.JFXGrid;

public class App extends Application {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        JFXGrid grid = new JFXGrid();
    }

}
